config/routes.rb
Rails.application.routes.draw do
devise_for :users
   root 'users#index'
   get 'users/new'
   post 'users/create'
   put 'users/:id', to: 'users#update', as: :users_update
   get 'users/list'
   get 'users/show'
   get 'users/:id/edit', to: 'users#edit' , as: :users_edit
   delete 'users/delete'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
 # guest user (not logged in)
    if user.role == "Admin"
      can :manage, :all
    else
      can [:index], User, id: user.id
      can [:show],User, id: user.id
      can [:edit],User, id: user.id
      can [:update], User,id: user.id
      can [:delete],User, id: user.id
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


after_initialize :default_values

  private
    def default_values
      self.role ||= "Non-admin"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_filter :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    render :file => "#{Rails.root}/public/403.html", :status => 403, :layout => false
    ## to avoid deprecation warnings with Rails 3.2.x (and incidentally using Ruby 1.9.3 hash syntax)
    ## this render call should be:
    # render file: "#{Rails.root}/public/403", formats: [:html], status: 403, layout: false
  end

  rescue_from ActiveRecord::RecordNotFound, :with => :render_404

  def render_404
    render :file => "#{Rails.root}/public/404.html", :status => 404,:layout =>false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :authenticate_user!
load_and_authorize_resource

  def index
    if current_user.role ==  "Admin"
      @users = User.all
    else
      @user = User.find(current_user.id)
   end
    redirect_to new_user_registration_path if current_user.nil?
    respond_to do |format|
      format.html
    end
  end

   def show
     @user = User.find(params[:id])
     respond_to do |format|
        format.html
     end
   end

   def new
    @user = User.new
   end

   def create
    @user = User.new(user_params)
    @user.role = 'Non-admin'

   if @user.save
      redirect_to :action => 'index'
   else
      render :action => 'new'
   end
   end

   def user_params
      params.require(:user).permit(:first_name, :last_name, :age, :biography, :email)
   end

   def edit
    @user = User.find(params[:id])
    respond_to do |format|
      format.html
    end
   end

   def update
    params.inspect
    @user = User.find(params[:id])

   if @user.update_attributes(user_params)
      redirect_to :action => 'show', :id => @user
   else
      render :action => 'edit'
   end
   end

   def delete
    User.find(params[:id]).destroy
   redirect_to :action => 'index'
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<h5>Logged in as <strong><%= current_user.email %></strong> <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "small button"  %></h5>

app/views/layouts/_header.html.erb
<!-- <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <h4> <%= link_to "USERS APPLICATION", '#', id: "logo" %></h4>
  </div>
</header>
 -->
 <h1>User Management System</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Registered Users</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="jumbotron">
  <div class="container">
  <% if user_signed_in? %>
  <!-- <img src="http://placekitten.com/g/1500/300"/> -->
  <%end %>
    <%= yield %>
  </div>
  </div>
  </body>
  <% if user_signed_in? %>
  <%= render 'layouts/footer' %>
  <% else %>
  <h5> Copyright reserved </h5>
  <%end%>
</html>

app/views/users/edit.html.erb
<%= form_for @user , :as => :user, :url => users_update_path(@user), :method => :PUT do |f| %>
  <%= f.label :first_name %>:
  <%= f.text_field :first_name %><br>

  <%= f.label :last_name %>:
  <%= f.text_field :last_name %><br>

  <%= f.label :age %>:
  <%= f.number_field :age %><br>

  <%= f.label :biography %>:
  <%= f.text_field :biography %><br>

  <%= f.label :email %>:
  <%= f.text_field :email %><br>

  <%= f.submit :class => 'small button' %>
<% end %>
<%= link_to 'HOME', root_path,  method: :get, class: "small button" %>

app/views/users/index.html.erb
<table id="albums" cellspacing="0">
  <thead>
    <tr>
      <th>        NAME        </th>
      <th>        EMAIL       </th>
      <% if current_user.role == "Admin" %>
      <th>        EDIT        </th>
      <th>        SHOW        </th>
      <th>        DESTROY     </th>
      <% end %>
      <th colspan="15"></th>
    </tr>
  </thead>
<% if current_user.role == "Admin" %>
<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.email %></td>
    <% if can? :edit, user %>
    <td><%= link_to 'Edit', users_edit_path(id: user.id), class: "small button"%></td><% end %>
    <% if can? :show, user %>
    <td><%= link_to 'Show', users_show_path(id: user.id), class: "small button"%></td><% end %>
    <% if can? :delete, user %>
    <td><%= link_to 'Destroy', users_delete_path(id: user.id),  method: :delete, data: { confirm: 'Are you sure?' } , class: "small button"%></td>
    <% end %>
  </tr>
<% end %>
<% else %>
<tr>
    <td><%= @user.first_name %></td>
    <td><%= @user.email %></td>
    <% if can? :edit, User %>
    <td><%= link_to 'Edit', users_edit_path(id: @user.id), class: "small button" %></td><% end %>
    <% if can? :show, User %>
    <td><%= link_to 'Show', users_show_path(id: @user.id), class: "small button" %></td><% end %>
    <% if can? :delete, User %>
    <td><%= link_to 'Destroy', users_delete_path(id: @user.id),  method: :delete, data: { confirm: 'Are you sure?' } , class: "small button"%></td> <% end %>
  </tr>
<%end %>
</table>

<%#= link_to 'Change password', edit_user_registration_path,  class: "small button" %>

app/views/users/show.html.erb
<br>
<br>
<h3>User details</h3>
<table id="albums" cellspacing="0">
  <thead>
    <tr>
      <th>FIRSTNAME</th>
      <th>LASTNAME</th>
      <th>EMAIL</th>
      <th>BIOGRAPHY</th>
      <th>AGE</th>
      <th colspan="20"></th>
    </tr>
  </thead>
  <tr>
    <td> <%= @user.first_name %> </td>
    <td> <%= @user.last_name %> </td>
    <td> <%= @user.email %> </td>
    <td> <%= @user.biography %> </td>
    <td> <%= @user.age %> </td>
  </tr>
</table>
<% if can? :edit, User %>
 <%= link_to '  Edit  ', users_edit_path(id: @user.id) , class: "small button"%>
 <% end %>
 <% if can? :delete, User %>
<%= link_to 'Delete     ', users_delete_path(id: @user.id),  method: :delete, data: { confirm: 'Are you sure?' }, class: "small button" %> <% end %>
<%= link_to 'HOME', root_path,  method: :get, class: "small button" %>